### ISSUE TITLE
Fix/check word count function

### ISSUE THREAD

**Issue by katberge** [Carsonthemonkey/Audio-Summary-App#9]
Giving over 700 when about 300 words shown on screen (however, this is in debug mode so it might work with the API calls)

**Comment by Carsonthemonkey** [comment]
The problem was actually with the debug text. It had excessive newline characters that would not be generated by the actual transcript. I have replaced it with one that is more simple, but if we add the ability to upload text files, or use a more advanced transcription method we may need to take another look at this issue.
